# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'giai_ma.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import qt_lsb
import cv2
import numpy as np
import backend
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = ".\\platform\\"

class Ui_giai_ma(object):
    def showhome(self):
        self.window_back = QtWidgets.QMainWindow()
        self.ui = qt_lsb.Ui_nhom1()
        self.ui.setupUi(self.window_back)
        self.window_back.show()
    ######################################################################
    def setupUi(self, giai_ma):
        giai_ma.setObjectName("giai_ma")
        giai_ma.resize(548, 359)
        self.label = QtWidgets.QLabel(giai_ma)
        self.label.setGeometry(QtCore.QRect(40, 20, 491, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        # Nhập file ảnh ############################################################################
        self.out_anh = QtWidgets.QLineEdit(giai_ma)
        self.out_anh.setGeometry(QtCore.QRect(190, 130, 201, 31))
        self.out_anh.setObjectName("out_anh")
        # Quay lại ############################################################################
        self.back = QtWidgets.QPushButton(giai_ma)
        self.back.setGeometry(QtCore.QRect(160, 190, 75, 23))
        self.back.setObjectName("back")
        self.back.clicked.connect(self.showhome)
        self.back.clicked.connect(giai_ma.close)

        # Bắt đầu ############################################################################
        self.bat_dau = QtWidgets.QPushButton(giai_ma)
        self.bat_dau.setGeometry(QtCore.QRect(290, 190, 75, 23))
        self.bat_dau.setObjectName("bat_dau")
        self.bat_dau.clicked.connect(self.backend_giaima)
        #######################################################################################
        self.label_2 = QtWidgets.QLabel(giai_ma)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(giai_ma)
        self.label_4.setGeometry(QtCore.QRect(140, 130, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(giai_ma)
        self.label_3.setGeometry(QtCore.QRect(240, 100, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.retranslateUi(giai_ma)
        QtCore.QMetaObject.connectSlotsByName(giai_ma)
###############################################################################################
    def backend_giaima(self):
        print("Giải mã")
        in_f=self.out_anh.text() #Ảnh mã hóa
        out_f= "Thông_điệp.txt"
        print(in_f)
        print(out_f)
        in_img = cv2.imread(in_f)
        steg = backend.LSBSteg(in_img)
        lossy_formats = ["jpeg", "jpg"]
     # giải mã ####################################################
        raw = steg.decode_binary()
        with open(out_f, "wb") as f:
            f.write(raw)

    def retranslateUi(self, giai_ma):
        _translate = QtCore.QCoreApplication.translate
        giai_ma.setWindowTitle(_translate("giai_ma", "Giải Mã"))
        self.label.setText(_translate("giai_ma", "GIẤU TIN TRONG ẢNH MÀU BẰNG LSB"))
        self.back.setText(_translate("giai_ma", "Quay Lại"))
        self.bat_dau.setText(_translate("giai_ma", "Giải Mã"))
        self.label_2.setText(_translate("giai_ma", "Nhóm 1"))
        self.label_4.setText(_translate("giai_ma", "Ảnh"))
        self.label_3.setText(_translate("giai_ma", "GIẢI MÃ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    giai_ma = QtWidgets.QWidget()
    ui = Ui_giai_ma()
    ui.setupUi(giai_ma)
    giai_ma.show()
    sys.exit(app.exec_())
